### PR TITLE
Add vaccines dose

### PR DESCRIPTION
**Pull request by misaka**
Doses are assumed to be `ml` until we see otherwise.

image

### CODE REVIEW

**Review by tvararu — APPROVED** [review]
As long as we won't need to perform arithmetic with dose values, this should be fine 👍

**Comment by paulrobertlloyd** [comment]
> As long as we won't need to perform arithmetic with dose values, this should be fine

For nasal Flu vaccine, if only one sprayed up one nostril, you would record that as half a dose. Perhaps the same is true with a partial injection. Which is to say, there _might_ be arithmetic.

**Comment by misaka** [comment]
> As long as we won't need to perform arithmetic with dose values, this should be fine 👍

What's the issue with doing arithmetic?

**Comment by misaka** [comment]
> > As long as we won't need to perform arithmetic with dose values, this should be fine 👍
> 
> What's the issue with doing arithmetic?

Sorted in Slack, AR will turn `decimal` types into `BigDecimal` in Ruby so there shouldn't be any issues.

**Pull request merged**
