### PR TITLE
Log id token when cis2 auth errors

### PR DESCRIPTION
**Pull request by misaka**
We've had some issues where an exception is raised while we process smartcard logisn. This should help us debug them better.

### CODE REVIEW

**Review by thomasleese — APPROVED** [review]
Another option could be to sent this information to Sentry, but this works too.

**Comment by misaka** [comment]
> Another option could be to sent this information to Sentry, but this works too.

Good idea. Do you remember how to do that offhand?

**Comment by misaka** [comment]
`with_scope` seems like a good candidate. https://docs.sentry.io/platforms/ruby/guides/rack/enriching-events/scopes/#using-with-scope

**Comment by thomasleese** [comment]
> `with_scope` seems like a good candidate. https://docs.sentry.io/platforms/ruby/guides/rack/enriching-events/scopes/#using-with-scope

Yeah, that's the one, and then you can add `context` here: https://docs.sentry.io/platforms/ruby/enriching-events/context/

**Pull request merged**
